apiVersion: v1
kind: service
metadata:
  name: hueapp
spec:
  selector:
    app: hueapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodeport: 30000
    type: LoadBalancer
